### ISSUE TITLE
Not working for 0.13

### ISSUE THREAD

**Issue by Zorelord** [andruzzzhka/BeatSaberMultiplayer#102]
Edit: Had to fix the version I had it at 0.30 lol

**Comment by ShadowMax** [comment]
For **0.13**(.0p1) I guess.

**Comment by Assistant** [comment]
Maybe Zorelord comes from the future

**Comment by BeigeAnimal** [comment]
Not really an issue considering the game was updated and the mod is being worked on for 0.13. it's known that previous release wasn't going to work on 0.13 didn't know what you expected tbh.

**Comment by ShadowMax** [comment]
Personally, I didn't expect anything. But that deserves to make a mentioning)

**Comment by Wiesbadenfinest** [comment]
Hi there, I'm no to all, I want to start my own hub, becuase the most of them have bad pings in germany, can some one please tell me, how to set the hub online, I can find it, but only over the 127.0.0.1 ip, and I don't know how to change to my puplic, I tried a lot, but nothing worked
