### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by kobaloi147** [andruzzzhka/BeatSaberMultiplayer#104]
I just installed this mod, along with a few others, and since adding this one to my list of mods whenever I play a song it will freeze part way through and the music continues to play to the end but won't fail me. Removing the .dll's provided in the Beat Saber_Data folder makes the game work fine, but I can't select "Rooms" or "Radio" in the multiplayer menu.

**Comment by kobaloi147** [comment]
![Capture](https://user-images.githubusercontent.com/25447502/55201133-fbec7500-5197-11e9-817f-94410bb8d85f.PNG)

**Comment by kobaloi147** [comment]
I should also state that I'm trying to play solo songs, since my friend is not online to set up this mod or play.

**Comment by andruzzzhka** [comment]
Could you please send your full Beat Saber root folder? I can't reproduce the problem with the same mods installed, so I think the difference is in the config files or something else

**Comment by kobaloi147** [comment]
I'm uploading it to Dropbox now since it's too large to be direct. This should be a fresh install of the game only things changed are mods, the two .dll's, and the custom song tracks.

**Comment by kobaloi147** [comment]
Oh, a few custom sabers as well, but that should be all.

https://www.dropbox.com/s/x1s1q442mh6nn8f/Beat%20Saber.zip?dl=0

**Comment by kobaloi147** [comment]
Oh the .dll's aren't in there, I forgot to check for those, I removed them to allow my nieces and nephews try the game.

**Comment by andruzzzhka** [comment]
Alright, with your files I was able to reproduce the problem! Now it's time to fix it

**Comment by andruzzzhka** [comment]
I think I found the cause of the crashes, for some reason Rumble Enhancer conflicts with multiplayer if you choose grip as the push-to-talk button in the settings

**Comment by kobaloi147** [comment]
Oh okay. Thank you so much for looking into it for me, I'm completely new to VR things and had no idea where to go with it. I'll try to change that setting or just remove the mod since I don't notice much difference anyways and hopefully that fixes my problem. :)
