### ISSUE TITLE
Cannot find BeatSaberMultiplayer in ModSaber Installer for version 0.13.1

### ISSUE THREAD

**Issue by Jordank321** [andruzzzhka/BeatSaberMultiplayer#107]
When I go to the modsaber installer, for the latest version (currently 0.13.1) I dont see the multiplayer mod

![image](https://user-images.githubusercontent.com/19892506/55434729-296a6180-5590-11e9-9142-f23022c51ffe.png)

**Comment by Assistant** [comment]
That's intended behavior. It only shows approved mods for each version.
