### ISSUE TITLE
ServerHub ping is not always displayed

### ISSUE THREAD

**Issue by ShadowMax** [andruzzzhka/BeatSaberMultiplayer#109]
![image of bsmp ping issues](https://i.imgur.com/9wRLowK.png)

Maybe will be better move it to second line or increase the width of the strings.

**Comment by andruzzzhka** [comment]
This is already done in 0.6.2.1 :)
![image](https://user-images.githubusercontent.com/18101504/55683110-445d1d00-5966-11e9-8fcb-9e969578501f.png)

**Comment by ShadowMax** [comment]
Yeah, cool! I notice this after posting the message. Thank you :)
