### ISSUE TITLE
v0.6.2.1 not working in beat saber 0.13.2?

### ISSUE THREAD

**Issue by scrumpyman** [andruzzzhka/BeatSaberMultiplayer#110]
The changelog on the release doesn't actually mention compatibility was updated for the newest version, but there was a commit for 0.13.2 compatability, so is it supposed to be working? It doesn't seem to be working for me. Custom avatars are showing up fine.

**Comment by andruzzzhka** [comment]
Yes, it should work on 0.13.2, so could you make sure you installed it correctly? You need to extract zip to the Beat Saber root folder

**Comment by scrumpyman** [comment]
It worked after I reinstalled everything, wouldnt show up no matter what otherwise.
