### ISSUE TITLE
Not working anymore with 1.0.0

### ISSUE THREAD

**Issue by DunklerPhoenix** [andruzzzhka/BeatSaberMultiplayer#111]
Hello,
Version v0.6.2.1 of BeatsaberMultiplayer does not work anymore with Beatsaber 1.0.0
Are there plans to make an update?

Greetings
Marco

**Comment by andruzzzhka** [comment]
I'm working on it :)
![image](https://user-images.githubusercontent.com/18101504/58256644-9254a580-7d99-11e9-85ed-6c7e00964ecd.png)

**Comment by DunklerPhoenix** [comment]
xD How epic.
Thanks
