### ISSUE TITLE
Lag Over Time

### ISSUE THREAD

**Issue by Melopod** [andruzzzhka/BeatSaberMultiplayer#113]
When in a multiplayer lobby, lag increases procedurally until the only way to fix the lag is to entirely restart the game. It seems to affect people joining a host worse, and also affect joiners when they were initially host and have left and rejoined the lobby. Lag in the sense of regular jumps in both the chart moving and player movements, increasing in interval until the game is pretty much unplayable. 
It only seems to really affect one person joining the lobby at a time.
Clip of when it started really affecting me in game + lag continues in the menus when going to quit the game https://www.twitch.tv/videos/430505175

**Comment by andruzzzhka** [comment]
Why did you close the issue? Because I didn't answer, or because it fixed itself? If the former, then I just haven't been able to reproduce the problem yet

**Comment by Melopod** [comment]
oop my bad. yeah it seems to have fixed itself with the newest update. Haven't been affected by it since.

**Comment by draven22** [comment]
This is still happening to me. Latest update. If you play anywhere between 5-10 songs the graphics will start to lag until you are lucky to be getting 10 fps.
This only happens in multiplayer. Not sure if there is some kind of leak.
