### ISSUE TITLE
Can't play with other people in 0.6.3.1 (help)

### ISSUE THREAD

**Issue by BanMars** [andruzzzhka/BeatSaberMultiplayer#116]
somethings happening on this version right now.
idk why but when my friends join my room (this situation is happend on my hub and offical hub)
 1 of my friend didn't move with loading avatar and sit on middle,but actually he was moving on his game and he said he can see our movement and avatars.

after that we started the song but the game didn't work well. when we hit notes,score didn't up. and suddely our controller's vivration has removed. and the result screen didn't show the player and score. (and our glitched friend kicked out the server!) like spectator mode!

after the song finished,i recreate the room and i glitched like my friend and they can't see my avatar and movement.
we tried other server. and we knew there's no errors on my server.

and on the previous version, v0.6.3.0 we are fine! nothing happend like upper version.
but as you guys know,this version can't see the avatar! ;-;

is there anyone experience this one? i want to know how to fix it!
and if there is no one know about this thing, i hope this glitch or bug gonna be fix!

**Comment by PlasmaPower** [comment]
Try enabling voice chat: #118. You can set the volume to 0.
