### ISSUE TITLE
Echo in voice chat

### ISSUE THREAD

**Issue by shrubin** [andruzzzhka/BeatSaberMultiplayer#117]
When I played with my friend with push to talk off, there was a pretty frequent echo. It wouldn't echo everything said, but pretty often a sound from a few seconds ago would repeat, and then continue repeating every few seconds. With push to talk on it only happened while the mic was active, but it similarly would play sounds from a few seconds ago. We're both using Rift S.

**Comment by andruzzzhka** [comment]
*Hopefully* fixed
