### ISSUE TITLE
Mod (mostly) breaks if voice chat is disabled

### ISSUE THREAD

**Issue by PlasmaPower** [andruzzzhka/BeatSaberMultiplayer#118]
If voice chat is disabled, and has been disabled since the game launched, `InGameController.voiceChatListener` is null which causes Update to throw a null reference exception before updating player info: https://github.com/andruzzzhka/BeatSaberMultiplayer/blob/81be378687ada2dcd1a5f54cb141de9689e12ce9/BeatSaberMultiplayer/InGameOnlineController.cs#L540

This causes most parts of multiplayer to not work, including score updates, avatar position, and download status, but song selection works fine. The symptoms are that of #116 (I suspect the player getting kicked was caused by the server thinking no one was in the room or something, as I didn't have that symptom when only I had this problem).

**Comment by BanMars** [comment]
OMG i get it now!
Thx a lot! I'll test it tomorow!
have a nice day! :D

**Comment by andruzzzhka** [comment]
Can't believe I missed this! Thanks!

**Comment by andruzzzhka** [comment]
Fixed!
