### ISSUE TITLE
Online button missing in menu.

### ISSUE THREAD

**Issue by Chz18** [andruzzzhka/BeatSaberMultiplayer#120]
I've tried everything from redownloading the mod to deleting everything and uninstalling the game and reinstalling.  It's just not showing up for me.

**Comment by andruzzzhka** [comment]
Of course it doesn't work, it's not updated for Beat Saber v1.1.0 yet, but I'm working on it

**Comment by Chz18** [comment]
Gotcha, I know some of my mods didn't break and a buddy of mine still has the online option even after he updated to 1.1.0 so I was just confused. Thanks for the heads up and I appreciate your work.
