### ISSUE TITLE
How to connect to your own Hub or Server in game?

### ISSUE THREAD

**Issue by moonbreeze4** [andruzzzhka/BeatSaberMultiplayer#121]
I have downloaded ServerHub_win-64.zip, changed the setting file and it runs well on my second PC. How to find my own Hub in Beat Saber(mod already installed) ?

**Comment by andruzzzhka** [comment]
You need to put the IP address of the second PC in `UserData/BeatSaberMultiplayer.json` like this:
![image](https://user-images.githubusercontent.com/18101504/59566019-5359fd00-9084-11e9-85b6-a2b433debd20.png)
