### ISSUE TITLE
x out of x players downloaded song bug

### ISSUE THREAD

**Issue by sehyeon0** [andruzzzhka/BeatSaberMultiplayer#122]
When you are host of a lobby and you try to play a song that not everybody has downloaded, upon download it will say that they have downloaded it on the left panel but on the main panel under "play" it won't show that everyone has it and it won't put them into the song when you click start. 

In order to get by this, as host when you select a song, after everyone downloads, click "cancel" and re select the song then it works properly. 

clip to show for better reference : https://clips.twitch.tv/SteamyGracefulSangPhilosoraptor

**Comment by andruzzzhka** [comment]
Fixed!
