### ISSUE TITLE
Show other player blocks bug

### ISSUE THREAD

**Issue by stack33** [andruzzzhka/BeatSaberMultiplayer#123]
Other player blocks seems to spawn but don't move on v0.6.4.1.
We were both using custom avatars with FBT and with all settings in the right panel turned on except  "Separate avatar for multiplayer" and "Spectator mode".

**Comment by andruzzzhka** [comment]
Can you post your `_latest.log` from `Beat Saber/Logs` please?

**Comment by stack33** [comment]
So, I also tested the dll you posted on discord today, but it has the same issue.
I've attached the logs from both versions
[new.log](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/3316105/new.log)
[old.log](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/3316106/old.log)
