### ISSUE TITLE
Where is 7.1.4?

### ISSUE THREAD

**Issue by Bluscream** [andruzzzhka/BeatSaberMultiplayer#158]
I get "update available in game"
```
[INFO @ 11:53:23 | Beat Saber Multiplayer Lite] An update for the mod is available!
[INFO @ 11:53:23 | Beat Saber Multiplayer Lite] New mod version: 7.1.4
[INFO @ 11:53:23 | Beat Saber Multiplayer Lite] Current mod version: 7.1.3
```
however i can only find 0.6.4.4 :/

https://github.com/andruzzzhka/BeatSaberMultiplayer/releases

**Comment by andruzzzhka** [comment]
Yeah, because you're using Multiplayer Lite, but looking for the new version in the full Multiplayer version repository. 
Here is the link for the Multiplayer Lite repository: https://github.com/Zingabopp/BeatSaberMultiplayer/releases

**Comment by Bluscream** [comment]
Is there a difference between the two?

**Comment by andruzzzhka** [comment]
Yes, Multiplayer Lite doesn't have avatars, this is the most noticeable change. But Multiplayer Lite also has some small improvements over full Multiplayer here and there (like, Random song button, Steam Rich Presence, etc.)

**Comment by Bluscream** [comment]
Ooohh i see, why don't you work together and make avatars, etc. optional features?
