### ISSUE TITLE
Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by balu100** [andruzzzhka/BeatSaberMultiplayer#173]
After updating my ubuntu vps to 20.04 the ServerHub can't be launched due to a libssl error i suspect this is due some compatibility issue.(Already tried to install libssl-dev but it did not help)
![image](https://user-images.githubusercontent.com/5224983/80252694-0e293300-8678-11ea-8746-3e5ca122bfab.png)

**Comment by andruzzzhka** [comment]
Try running this:
```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6.2_amd64.deb 
```
Or try installing dotnet and running the dll file:
```
sudo apt-get install dotnet
dotnet ServerHub.dll
```

**Comment by balu100** [comment]
reinstalling libssl-dev and using your first method fixed the issue. Thanks

**Comment by nitrog0d** [comment]
The link for the libssl changed btw,
```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.4_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.4_amd64.deb
```
