### ISSUE TITLE
[Feature Request] Consistent releases.

### ISSUE THREAD

**Issue by joelixny** [andruzzzhka/BeatSaberMultiplayer#18]
It'd be useful if every release version included the plugin, the server, and the hub. Even if it's just the same zip from the previous release. That would allow us to safely link to the [latest](https://github.com/andruzzzhka/BeatSaberMultiplayer/releases/latest) without having to worry of it missing stuff in the future. It would also help with confused users.

**Comment by megalon** [comment]
I would also prefer this.
It would be one less thing to troubleshoot.
