### ISSUE TITLE
(client) Server list back-button does not do anything

### ISSUE THREAD

**Issue by SirCoolness** [andruzzzhka/BeatSaberMultiplayer#19]
I am having this issue in both patch 0.4.4.1 and patch 0.4.4.2. For diagnostic reasons I checked if it works on patch 0.4.4 and it seems to be mapped correctly. 

Beatsaber Version:
0.10.2p1

Hardware:
HTC Vive 

(I also have seen this issue with my friend who plays on the oculus rift, but he uses steamvr)

**Comment by andruzzzhka** [comment]
Fixed in 0.4.5.0
