### ISSUE TITLE
ServerHub for Linux, Syntax error

### ISSUE THREAD

**Issue by factoryal** [andruzzzhka/BeatSaberMultiplayer#44]
Hi, I'm setting up the server hub to my arm-based single board computer.
SBC: Pine A64+
OS: DietPi (Debian8 Jessie)

![image](https://user-images.githubusercontent.com/22570054/45538493-30bf5d00-b842-11e8-8bfc-7fc581bf0a9e.png)
```
root@DietPi:/etc/beatsaber-serverhub/ServerHub_linux-arm# sh ./ServerHub
./ServerHub: 1: ./ServerHub: Syntax error: word unexpected (expecting ")")
```
Running the file, there's an error message.
What is the problem, and can I fix it manually?

**Comment by andruzzzhka** [comment]
`ServerHub` file is not an sh script.
You need to run `./ServerHub` (without `sh`)

**Comment by factoryal** [comment]
![image](https://user-images.githubusercontent.com/22570054/45539548-0327e300-b845-11e8-85d1-2b7d8121d2fe.png)
``` sh
root@DietPi:/etc/beatsaber-serverhub/ServerHub_linux-arm# ls -al | grep "Server"
-rw-r--r-- 1 root root   19456 Jul 26 13:35 ServerCommons.dll
-rw-r--r-- 1 root root    6004 Jul 26 13:35 ServerCommons.pdb
-rw-r--r-- 1 root root   67684 Jul  5 23:42 ServerHub
-rw-r--r-- 1 root root   21588 Jul 26 13:35 ServerHub.deps.json
-rw-r--r-- 1 root root   21504 Jul 26 13:35 ServerHub.dll
-rw-r--r-- 1 root root    5012 Jul 26 13:35 ServerHub.pdb
-rw-r--r-- 1 root root      28 Jul 26 13:35 ServerHub.runtimeconfig.json
```
Do I have to set executable flag?

**Comment by andruzzzhka** [comment]
Yup, and install libunwind-dev

**Comment by factoryal** [comment]
![image](https://user-images.githubusercontent.com/22570054/45539904-05d70800-b846-11e8-9164-a9218beb9ccb.png)
```
vkdlsvnt@DietPi:/etc/beatsaber-serverhub/ServerHub_linux-arm$ ls -al | grep "ServerHub"
-rwxr--r-- 1 root root   67684 Jul  5 23:42 ServerHub
-rw-r--r-- 1 root root   21588 Jul 26 13:35 ServerHub.deps.json
-rw-r--r-- 1 root root   21504 Jul 26 13:35 ServerHub.dll
-rw-r--r-- 1 root root    5012 Jul 26 13:35 ServerHub.pdb
-rw-r--r-- 1 root root      28 Jul 26 13:35 ServerHub.runtimeconfig.json
vkdlsvnt@DietPi:/etc/beatsaber-serverhub/ServerHub_linux-arm$ sudo ./ServerHub
sudo: unable to execute ./ServerHub: No such file or directory
```

Still not working.
Is this my problem?

**Comment by andruzzzhka** [comment]
It looks like you can't run 32-bit executables on 64-bit ARM, so you can try installing `dotnet` and running `dotnet ./ServerHub.dll`

**Comment by stewartgill1977** [comment]
I also are playing with a Linux server and get this error 

root@kali:~/server# cd
root@kali:~# chmod +x server
root@kali:~# cd server
root@kali:~/server# ./ServerHub

Unhandled Exception: System.InvalidOperationException: The terminfo database is invalid.
at System.TermInfo.Database..ctor(String term, Byte[] data)
at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
at System.TermInfo.Database.ReadDatabase(String term)
at System.TermInfo.Database.ReadActiveDatabase()
at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__27_0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Lazy`1.CreateValue()
at System.ConsolePal.WriteResetColorString()
at System.ConsolePal.RefreshColors(ConsoleColor& toChange, ConsoleColor value)
at ServerHub.Misc.Logger.PrintLogMessage(LogMessage msg) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Misc\Logger.cs:line 81
at ServerHub.Misc.Logger.Exception(Object msg, Boolean hideHeader) in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Misc\Logger.cs:line 68
Aborted
root@kali:~/server#
