### ISSUE TITLE
Can't see players after song

### ISSUE THREAD

**Issue by LunarTiger** [andruzzzhka/BeatSaberMultiplayer#49]
In the latest release (0.5.1.5) after playing a song I can't see the other players in the results or in the lobby, but when I select another song and start it we can then see each other again until the end of the song. I'll include my log file if it helps.
[0.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2424974/0.txt)

**Comment by andruzzzhka** [comment]
Can you please send MPLog.txt from Beat Saber folder?

**Comment by andruzzzhka** [comment]
Yeah, it should be useful

**Comment by LunarTiger** [comment]
Here's Jack's
[MPLog.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2429104/MPLog.txt)
[output_log.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2429105/output_log.txt)

And Paul's
[MPLog.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2429106/MPLog.txt)
[output_log.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2429107/output_log.txt)
