### ISSUE TITLE
Online button not clickable

### ISSUE THREAD

**Issue by Hexbugman213** [andruzzzhka/BeatSaberMultiplayer#53]
I recently updated the mod to the latest version, only for it to stop working. It loads, but clicking "online" does nothing.

I have tried with my current mods, and with the bare bones (files included and custom songs), i have also tried with no custom songs.
these are screenshots of my CURRENT mod layout.
https://puu.sh/BVUfa/6945431daa.png
https://puu.sh/BVUfu/2de5693d7b.png
https://puu.sh/BVUfG/4ea8b392a3.png
nobody on the discord knows, since everything's updated.
if you need any more info, just ask.

**Comment by Assistant** [comment]
Maybe try renaming your `CustomAvatar(1).dll` to `CustomAvatar.dll`.
Every time I've seen that issue it has been because Custom Avatar is missing.
