### ISSUE TITLE
[Feature Request] Kick User or send to blacklist

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#57]
HI can you please add a command to kick a single user with a pop up box with the reason why for server admin. This way the admin can choose to just kick or add to blackilst maybe even have a option select eg press 1 to kick user ......... or 2 to send user to blacklist.

thanks

**Comment by andruzzzhka** [comment]
There is already a console command for this: 
`blacklist [add/remove] [nick/playerID/IP]`
Why it is not suitable for you?

**Comment by stewartgill1977** [comment]
ooo yes you are right blacklist :) what about a single kick tho?. I use to be able to kick single users a long time ago but i think that command was removed.
