### ISSUE TITLE
Support room adjust setting

### ISSUE THREAD

**Issue by samuelmaddock** [andruzzzhka/BeatSaberMultiplayer#59]
When the local player has a room offset applied, the networked player location won't be adjusted for other players. The local player will see the other networked players correctly oriented though.

Steps to reproduce:
1. Launch Beat Saber.
1. Configure the Room Adjust setting to include an offset and rotation.
1. Join a networked lobby with other players.

Observe that other players don't see you where you're standing in your local game.

**Comment by andruzzzhka** [comment]
Should now be fixed!
