### ISSUE TITLE
beatsaber server crash and restart batch script

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#61]
sorry im new to this Linux os for the server automatic restart on crash i see the script on the site and i understand to place it in the serverhub dir but what do i save the files as whats the extension type how do i make the files. Is there somewhere a can download them and just edit my details into them. thanks for your help

**Comment by andruzzzhka** [comment]
I don't really use Linux either, so I don't know, but you can ask in [Beat Saber Modding Group](https://discord.gg/beatsabermods) Discord to help you

**Comment by stewartgill1977** [comment]
Ok thanks
