### ISSUE TITLE
Lobby full of people

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#62]
Hi i have noticed a few times now that the lobby gets full of people right now i have over 80 people in the lobby and 8 rooms. Is there a way to empty it as i know they must be dead connections or something. I thought it emptied it self after a wile but that does not seem to be happening or not all the time.

**Comment by stewartgill1977** [comment]
today i got 260 clients just in the lobby with 6 rooms open its the program not meany to kick the connections that have disconnected? im shore there is not 260 live connections if there is only 6 rooms

**Comment by andruzzzhka** [comment]
I will fix this in 0.5.4.0 which will be out in a couple of days
You can try to build it from [this commit](https://github.com/andruzzzhka/BeatSaberMultiplayer/commit/724bc7e5575bec6c3fe7960ac62f343ceb0cd397) yourself

**Comment by andruzzzhka** [comment]
Should now be fixed!
