### ISSUE TITLE
New Ver 0.5.4.0 Button Not Clickable 

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#65]
Not sure whats going on but i copied the new files over to beatsaber and replaced them. When i lunch the game the online is there and lit up but not clickable. If i use the install/update in the mod manager the online is clickable but the hub will not show and is says a update is available in the game so i try to replace the files again and the online button in game once again is not clickable have i done something wrong when installing?

**Comment by stewartgill1977** [comment]
i installed the new hub to the server and the plugins to beatsaber

**Comment by MDReckless** [comment]
Having the same issue here. Had to update to this version since I couldn't make a room but now the button lights up like it's active but won't let me press it.

**Comment by stewartgill1977** [comment]
Ver 5.4.1 is working :)
