### ISSUE TITLE
[Feature Request] Don't download songs to my main library

### ISSUE THREAD

**Issue by Trentflix** [andruzzzhka/BeatSaberMultiplayer#68]
Just started using the mod and am super-impressed but was immediately dismayed that when entering a lobby I started downloading 100+ songs I don't want in my main music library. It would be nice if they were placed somewhere so I don't have to download them again but also so they don't clutter up my main song library. I guess I could favorite "my" songs and filter on that but I'd rather not have to do that.

**Comment by andruzzzhka** [comment]
Unfortunately this is a limitation of the Song Loader, so the best I can do is to download songs to a subfolder of the CustomSongs folder

**Comment by andruzzzhka** [comment]
Done!
