### ISSUE TITLE
[Feature Request] Message All Rooms In Bulk 

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#72]
Hi i know there is a message option already but i would like to be able to send to all rooms in bulk. Eg i had to do a server firewall firmware update this meant all users got kicked when the connection to the net was taken down for the update. If there was a way to worn everyone i would of did a bulk message post saying the hub will be going down in 5min for a server update and will take around 3min. I not sore if this can be done already or its just single rooms one at a time. Also a default message that could be customized to all new rooms or a user when they first enter that sets out rules or just a nice welcome to ------- server hub would be nice. :)

**Comment by andruzzzhka** [comment]
Done!
