### ISSUE TITLE
Can't see any Avatars or the Scoreboard ingame

### ISSUE THREAD

**Issue by VioletChaolan** [andruzzzhka/BeatSaberMultiplayer#80]
I can't see any other players at any time at all. i can still see rooms fine even open them and start songs with other players its just that the scoreboard and avatars dont exist at all. i already reinstalled everything and looked at the json which is also set correctly so yeah i got nothing.

**Comment by andruzzzhka** [comment]
Please send `MPLog.txt` from your Beat Saber folder and `output_log.txt` from `%appdata%\..\LocalLow\Hyperbolic Magnetism\Beat Saber`

**Comment by VioletChaolan** [comment]
here ya go.
[MPLog.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2848612/MPLog.txt)

[output_log.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2848616/output_log.txt)
I deleted 44mb of the same error btw because it wouldnt fit otherwise it was allways spamming the same "(Filename: <b568cc31d280454bacc3813c94e1fba9> Line: 0)

UnityException: Transform child out of bounds
  at (wrapper managed-to-native) UnityEngine.Transform.GetChild(UnityEngine.Transform,int)
  at BeatSaberMultiplayer.UI.ViewControllers.RoomScreen.SongSelectionViewController.Update () [0x00019] in <b568cc31d280454bacc3813c94e1fba9>:0 "

**Comment by andruzzzhka** [comment]
Please try renaming your Plugins folder and install ONLY multiplayer (with dependecies).  I think it might be a conflict with some mod

**Comment by VioletChaolan** [comment]
yeah alright so i looked into it and its gameplay modifies plus in the modsaber installer everything else works fine. i only use modsaber installer.
