### ISSUE TITLE
wss setup

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#81]
Is there any way to make it easier to get the hub to show on the web site. I can not get the reverse proxy to work and i don't think i can anyway because i have port 443 going to another server on the network that does not run the hub and as far a i know you can not point a port to two different locations on the same network ( i could be wrong) It would be really good to be able to just click and run the hub as im not up there with linux os so finding it hard to get the thing running on wss. The hub itself it running fine and there are users on it just can't get it on wss to have it listed on the site.

thanks

**Comment by andruzzzhka** [comment]
You don't need port 443 to run a reverse proxy, you can use any port for that, and as far as I know, you don't even need a landing page for your hub to appear on the site. Ask Assistant#8431 to add your hub to the list

**Comment by stewartgill1977** [comment]
Assistant#8431 will not add a site to the hub in till its running on wss. I still have users using my hub as its in the list i think but want it on the site and cos its Linux i don't know much about it. I have tried to setup reverse proxy but just cant get it to work. There must be a better way im guessing that's why all the other hubs are no longer listed cos its just a pain to set up now with the wss

**Comment by andruzzzhka** [comment]
I don't know much about Linux either, so I can't help setting up a reverse proxy, but I can try to make ServerHub capable of using WSS out of the box in 0.6.1.2

**Comment by stewartgill1977** [comment]
ooo yes please i really want to put my hub on the web page so if i could just install and go that would so soooo handy and im shore other that don't know Linux well like me will also like that. :)

**Comment by Assistant** [comment]
It's not that I don't want to add it if it doesn't have WSS, I just can't track the status of the hub without WSS, so it's pointless. You don't need a landing page, just WSS, and that doesn't need 443, it can be any port.

**Comment by stewartgill1977** [comment]
hopefully the next ver will have wss included in it and will make it a lot easier to set up :)
