### ISSUE TITLE
Unable to see my own scoreboard

### ISSUE THREAD

**Issue by Xenooooon** [andruzzzhka/BeatSaberMultiplayer#82]
I can see other people's scores during and after a song, but im not able to see my own, and other people cant see mine, and are able to see other peoples except me.

I have tried using version 6.0.0 (ModInstaller version), and manually installing 6.1.1 on mine and my friends (so we match each other)
I had Gameplay modifiers on the 6.0.0 try, then learned it didnt work so I installed the 6.1.1 version WITH gpm and it still didnt work, so I uninstalled GPM with version 6.1.1 of BSM and I still cant see my own score (as well as others unable to see mine)
If you would like me to attach any sort of file I havent, feel free to let me know, I can also load up BS and try with you (join your room) if you would like.

Im more available on discord @~Eden#0001 (im in BSMG)
Ill be posting files here though, cuz its better to keep records here for you :)

https://www.dropbox.com/s/fuhu95q3qzcn91h/Plugins.rar
My plugins folder ^
Everything except BSM is the version found in ModInstaller (since 2 days ago)
[MPLog.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2871879/MPLog.txt)
And heres my multiplayer log if that also helps.

**Comment by andruzzzhka** [comment]
Alright, I just tested with your Plugins folder, and everything works, so it's definitely not a plugin conflict. Could you please send your output_log.txt (`%appdata%\..\LocalLow\Hyperbolic Magnetism\Beat Saber`) and make sure you have all the dependencies installed (`Beat Saber_Data\Managed`) ?

**Comment by Xenooooon** [comment]
[output_log.txt](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2871905/output_log.txt)

I have verified I have Lidgren.Network.dll, NSpeex.dll, and CSCore.dll in my Beat Saber_Data\Managed

**Comment by andruzzzhka** [comment]
Can you send your UserData folder? (Don't forget to remove your OAuth key if you have any)

**Comment by Xenooooon** [comment]
[UserData.zip](https://github.com/andruzzzhka/BeatSaberMultiplayer/files/2892773/UserData.zip)
here you go

**Comment by andruzzzhka** [comment]
You had spectator mode turned on so you couldn't play on your own and had to watch other players, but this mode is most likely broken now and so you didn't see another player
![2019-02-22_14-13-24](https://user-images.githubusercontent.com/18101504/53226052-8aa73700-36ac-11e9-929b-38c476f7a335.png)

**Comment by andruzzzhka** [comment]
And i should probably fix spectator mode...
