### ISSUE TITLE
v0.6.1.2 Install cert

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#86]
Hi and thanks for including wss to the new ver. I still need help how do i get it running eg do i need to make a cert and put it into the install dir?. A step by step would be good if you have the time thanks

**Comment by andruzzzhka** [comment]
Yeah, you need a PKCS #12 cert
You can create it from *.pem cert like this: https://www.paypal.com/us/smarthelp/article/how-do-i-convert-my-pem-format-certificate-to-pkcs12-as-required-by-the-java-and-.net-sdks-ts1020
Then provide a path to this cert and export password in settings file

**Comment by stewartgill1977** [comment]
hmmm getting this error 

[EXCEPTION -- 00:01:01] Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got t. Path 'Server.WebSocketCertPath', line 12, position 26.
   at Newtonsoft.Json.JsonTextReader.ParseComment(Boolean setToken)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ServerHub.Misc.Settings.get_Instance() in C:\Users\andru_000\Source\Repos\BeatSaberMultiplayer\ServerHub\Misc\Settings.cs:line 573

**Comment by andruzzzhka** [comment]
What your Settings.json looks like?

**Comment by stewartgill1977** [comment]
{
  "Server": {
    "Port": 3700,
    "Tickrate": 30,
    "TryUPnP": true,
    "EnableWebSocketServer": true,
    "EnableWebSocketRoomInfo": false,
    "EnableWebSocketRCON": false,
    "RCONPassword": "changeme",
    "WebSocketPort": 3701,
    "SecureWebSocket": true,
    "WebSocketCertPath": "/home/stewart/.local/opt/ServerHub/treasurehunters.nz.p12",
    "WebSocketCertPass": "password",
    "ShowTickrateInTitle": true,
    "AllowEventMessages": true,
    "AllowVoiceChat": true,
    "ShowTickEventExceptions": false,
    "SendCrashReports": true
  },
  "Radio": {
    "EnableRadio": false,
    "NextSongPrepareTime": 90.0,
    "ResultsShowTime": 15.0,
    "RadioChannels": [
      {
        "ChannelName": "Radio Channel",
        "ChannelIconUrl": "https://cdn.akaku.org/akaku-radio-icon.png",
        "PreferredDifficulty": "Expert",
        "JoinMessages": [
          "{0} joined us!"
        ],
        "DefaultSongIDs": []
      }
    ]
  },
  "Logger": {
    "LogsDir": "Logs/"
  },
  "Access": {
    "Blacklist": [
      "76561201521433077",
      "IGGGAMES",
      "76561199437989403",
      "VALVE"
    ],
    "WhitelistEnabled": false,
    "Whitelist": []
  },
  "Misc": {
    "PlayerColors": {}
  },
  "TournamentMode": {
    "Enabled": false,
    "RoomNameTemplate": "Tournament Room {0}",
    "Rooms": 4,
    "Password": ""
  }
}

**Comment by andruzzzhka** [comment]
Looks fine to me

**Comment by stewartgill1977** [comment]
hmmmmmm :(

**Comment by andruzzzhka** [comment]
Can you please redownload latest release and try again?

**Comment by stewartgill1977** [comment]
Ok its running how do i check its working on wss? is there a test i can do

**Comment by stewartgill1977** [comment]
i used the site www.websocket.org/echo.html to test i see this error when i press connect stewart@stewart:~/.local/opt/ServerHub$ chmod +x ServerHub
stewart@stewart:~/.local/opt/ServerHub$ ./ServerHub
[LOG       -- 00:48:29] Beat Saber Multiplayer ServerHub v0.6.1.2
[LOG       -- 00:48:29] Found 0 plugins!
[LOG       -- 00:48:30] Hosting Secure WebSocket Server @ 101.100.139.145:3701
[LOG       -- 00:48:30] Hosting ServerHub @ 101.100.139.145:3700
[WARNING   -- 00:48:30] Use [Help] to display commands
[WARNING   -- 00:48:30] Use [Quit] to exit
>>> [LOG       -- 00:48:31] You have the latest version of ServerHub
[LOG       -- 00:48:48] Client version v600 tried to connect
[LOG       -- 00:49:12] Client version v600 tried to connect
[LOG       -- 00:49:37] Client version v600 tried to connect
[LOG       -- 00:50:07] Client version v600 tried to connect
[LOG       -- 00:50:15] Client version v600 tried to connect
[LOG       -- 00:50:20] Client version v600 tried to connect
[LOG       -- 00:50:27] Client version v600 tried to connect
23/02/19 12:50:32 AM|Error|ExecutionContext.Run|The requested security protocol is not supported.
23/02/19 12:50:51 AM|Error|ExecutionContext.Run|The requested security protocol is not supported.

**Comment by stewartgill1977** [comment]
i put in wss://treasurehunters.nz:3701

**Comment by andruzzzhka** [comment]
Can you try redownloading it _again_?

**Comment by stewartgill1977** [comment]
new error

tewart@stewart:~/.local/opt/ServerHub$ chmod +x ./ServerHub
stewart@stewart:~/.local/opt/ServerHub$ ./ServerHub
[LOG       -- 01:17:42] Beat Saber Multiplayer ServerHub v0.6.1.2
[LOG       -- 01:17:42] Found 0 plugins!
[LOG       -- 01:17:43] Hosting ServerHub @ 101.100.139.145:3700
[WARNING   -- 01:17:43] Use [Help] to display commands
[WARNING   -- 01:17:43] Use [Quit] to exit
>>> [LOG       -- 01:17:43] You have the latest version of ServerHub
[LOG       -- 01:17:45] Hosting Secure WebSocket Server @ 101.100.139.145:3701
[LOG       -- 01:17:46] Client version v600 tried to connect
[LOG       -- 01:17:46] Client version v600 tried to connect
23/02/19 1:17:51 AM|Error|ExecutionContext.Run|An exception has occurred while reading an HTTP request/response.
[LOG       -- 01:17:52] Client version v600 tried to connect
[LOG       -- 01:18:00] Client version v600 tried to connect

**Comment by andruzzzhka** [comment]
But does it work? I have the same error in the console, but it seems to work anyway

**Comment by stewartgill1977** [comment]
Im not shore BUT when i enter this address into the test site wss://hub.jogi-server.de/wss/ ot (from the https://bs.assistant.moe/Multiplayer/) site it comes up with all the info so not shore it its working cos it gives a diff reply.?

**Comment by andruzzzhka** [comment]
Try to open https://treasurehunters.nz:3701 for your browser to trust your certificate and try again

**Comment by stewartgill1977** [comment]
yep that worked

**Comment by andruzzzhka** [comment]
Where did you get this certificate?
![image](https://user-images.githubusercontent.com/18101504/53242907-bb9d6100-36d8-11e9-955f-21d364067a07.png)

**Comment by stewartgill1977** [comment]
i just found a free site that made it for me as i run the server here at home so i don't use a paid certificate. that's why i guess its coming up with the trust thingy

**Comment by andruzzzhka** [comment]
Why don't you use [Let's Encrypt](https://letsencrypt.org/getting-started/)?

**Comment by stewartgill1977** [comment]
tired that could not get it to work to complicated the site i used can't remember what it was all i had to do was enter a fue details and it downloaded it. the lets encrypt i could never get it to work

**Comment by andruzzzhka** [comment]
I mean, with your certificate, anyone who tries to connect to your server will have to get their browser to trust it

**Comment by stewartgill1977** [comment]
yea going to try lets encrypt see if i can get that to work
