### ISSUE TITLE
Voice Chat isn't working

### ISSUE THREAD

**Issue by HumanDude** [andruzzzhka/BeatSaberMultiplayer#89]
I went to try voice chat in multiplayer, everything was on that was needed to make it work. I also uninstalled beat saber and reinstalled it all yet voice chat was still broken. Idk why its not working but all i know is all i should have to do is install the mod, turn on voice chat if its disabled, then it should work.

**Comment by andruzzzhka** [comment]
If you have Push to talk enabled (it is enabled by default) , you need to press the grip button to talk (you can change this button in the settings)
If that doesn't help you, please send MPLog.txt from Beat Saber root folder and output_log.txt from `%appdata%\..\LocalLow\Hyperbolic Magnetism\Beat Saber`

**Comment by stewartgill1977** [comment]
there seems to be some bug with the voice chat if i enter any rooms with other players and have voice chat enabled it crashes beatsaber every time. If i disable it in the settings there is no crash

**Comment by andruzzzhka** [comment]
This is a bug in CSCore and I can't really fix it without getting rid of CSCore entirely (which I plan to do)
