### ISSUE TITLE
Hub Admin Using Web Browser

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#90]
Hi not shore who i should ask this but would it be possible to make a webpage to access the admin part like the cmd window. At the mo i am remote desktop into the server to run commands but it would be really nice to be able to load a admin window / page to do the same using the browser. maybe some way to remote control the hub command window over the browser with a live update of whats going on. Delete this if not possible just wanted to ask. :)

**Comment by andruzzzhka** [comment]
There is a [WebRCON](https://andruzzzhka.github.io/BeatSaberMultiplayer/) available, you just need to turn it on in hub settings

**Comment by stewartgill1977** [comment]
hmm i get a error 
![image](https://user-images.githubusercontent.com/37970956/53471466-8d00fb00-3ac9-11e9-84d9-2d1643a46099.png)

**Comment by stewartgill1977** [comment]
i have set to true and set a password as well in the config

**Comment by stewartgill1977** [comment]
never mind it works when i use the domain name and not the ip :)
