### ISSUE TITLE
Hub seems to be off line for some

### ISSUE THREAD

**Issue by stewartgill1977** [andruzzzhka/BeatSaberMultiplayer#91]
I seem to be having a strange problem my hub has been very quite and i have just found out that its showing offline in beatsaber for some users. I have had users connect today just not a lot is there a reason it would show offline for some and not others. On the hub site its showing online and the server is running

**Comment by andruzzzhka** [comment]
There is a bug that causes the client not to disconnect after receiving the list of rooms, and this, coupled with the max connections limit (32 by default), leads to this behavior

**Comment by stewartgill1977** [comment]
so if i restart the hub will that clear the connections? because i have done that a few times but still i see very few connections

**Comment by andruzzzhka** [comment]
> so if i restart the hub will that clear the connections?
Yeah, that should help
