### ISSUE TITLE
[ServerHub] Add option to disable Interactive Shell

### ISSUE THREAD

**Issue by jimnordb** [andruzzzhka/BeatSaberMultiplayer#96]
This is mainly for linux users running ServerHub in systemd as a service.

**Comment by Assistant** [comment]
I run it as a systemd service and the interactive shell is still very useful in that case.

**Comment by jimnordb** [comment]
It would only be an option. Rcon still makes it very viable to administrate

**Comment by stewartgill1977** [comment]
I love the Rcon its all i use now

**Comment by andruzzzhka** [comment]
Done!

**Comment by jimnordb** [comment]
Woho! thanks :D
