### ISSUE TITLE
[Feature Request] Per player difficulty

### ISSUE THREAD

**Issue by XeonBlue** [andruzzzhka/BeatSaberMultiplayer#97]
For songs that have multiple difficulties available, allow each player to select the difficulty they would like to play the song.  Would allow players of different skill levels to play together.  I have a friend just getting into VR and would be fantastic to play with him.

**Comment by andruzzzhka** [comment]
Do you think the scores should be compared directly or scaled according to the chosen difficulty?

**Comment by XeonBlue** [comment]
I wouldn't think that any scaling or comparing would be strictly necessary... maybe just include the difficulty along with the score on the results screen?  I expect people playing in this kind of mode would just be playing for fun and the experience of hanging out in game together.

**Comment by Marcsoup** [comment]
I agree with XeonBlue. I was playing last night with a friend who is way better than I am at Beat Saber and would love to be able to play on hard when she's on expert/expert+. I personally feel like a score is secondary to the fun of just hanging out and listening to my favorite songs with friends.

**Comment by Trentflix** [comment]
I really like this idea, beyond score though beyond score, I'd _also_ like to see the % which I think would be a little more comparable comparison across difficulties.
